
obj-$(CONFIG_QCI_FINPOINT)		+= qci_finpoint/
obj-$(CONFIG_QCI_VIBRATOR)		+= qci_vibrator/
obj-$(CONFIG_QCI_AUDIO_DEVICE)		+= qci_audiodev/
obj-$(CONFIG_QCI_SYS)			+= qci_sys/
obj-$(CONFIG_QCI_WLAN_POWER)       += qci_wlan_power/
obj-$(CONFIG_QCI_PMIC_RPC)       += qci_pmic_rpc/

